/**
 * Vi Consulting Finance — Blog Loader
 * Reads the articles registry and renders blog cards.
 * On Netlify: articles.json is auto-generated by a build plugin from the /content/blog/ markdown files.
 * Locally: we use a static articles.json for preview.
 */

// ─── Article Registry ─────────────────────────────────────────────────────────
// This array is the single source of truth for all articles.
// When you add a new article via Netlify CMS, this file is regenerated automatically.
// You can also add entries manually here in the same format.

const ARTICLES = [
  {
    slug: "come-funziona-linflazione",
    title: "Come funziona davvero l'inflazione — e perché i tuoi risparmi perdono valore ogni anno",
    date: "2025-02-18",
    category: "Educazione Finanziaria",
    categoryColor: "gold",
    excerpt: "L'inflazione non è solo un numero sul giornale. È il motivo per cui i soldi fermi sul conto corrente valgono meno ogni anno. Capire come funziona è il primo passo per proteggersi.",
    image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=80&auto=format&fit=crop",
    readtime: 8,
    access: "free"
  },
  {
    slug: "etf-guida-completa",
    title: "ETF: la guida completa per chi inizia a investire",
    date: "2025-02-05",
    category: "Investimenti",
    categoryColor: "sky",
    excerpt: "Cosa sono gli ETF, come funzionano e perché sono diventati lo strumento preferito dai piccoli investitori. Tutto quello che devi sapere prima di iniziare.",
    image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&q=80&auto=format&fit=crop",
    readtime: 12,
    access: "free"
  }
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatDate(dateStr) {
  const d = new Date(dateStr);
  return d.toLocaleDateString('it-IT', { day: 'numeric', month: 'short', year: 'numeric' });
}

function accessBadge(access) {
  if (access === 'pro') {
    return `<span class="blog-pro-badge">🔒 PRO</span>`;
  }
  return `<span class="blog-tag">FREE</span>`;
}

// ─── Determine root path (home vs blog subfolder) ─────────────────────────────
function articlePath(slug) {
  const isInBlogFolder = window.location.pathname.includes('/blog/');
  const prefix = isInBlogFolder ? '../blog/' : 'blog/';
  return `${prefix}${slug}.html`;
}

// ─── Render homepage preview (3 articles max, 2-column layout) ────────────────

function renderHomePreview() {
  const container = document.getElementById('homeBlogGrid');
  if (!container) return;

  const articles = ARTICLES.slice(0, 3);
  if (articles.length === 0) {
    container.innerHTML = '<p class="blog-loading">Nessun articolo ancora. Torna presto!</p>';
    return;
  }

  const main = articles[0];
  const others = articles.slice(1);

  let html = `
    <a href="${articlePath(main.slug)}" class="blog-card main">
      <div class="blog-img">
        <img src="${main.image}" alt="${main.title}" loading="lazy">
      </div>
      <div class="blog-body">
        <span class="blog-category ${main.categoryColor}">${main.category}</span>
        <h3 class="blog-title">${main.title}</h3>
        <p class="blog-excerpt">${main.excerpt}</p>
        <div class="blog-meta">
          <span>${formatDate(main.date)}</span>
          <span>·</span>
          <span>${main.readtime} min lettura</span>
          ${accessBadge(main.access)}
        </div>
      </div>
    </a>
  `;

  if (others.length > 0) {
    html += `<div class="blog-right-col">`;
    others.forEach(art => {
      html += `
        <a href="${articlePath(art.slug)}" class="blog-card">
          <div class="blog-img">
            <img src="${art.image}" alt="${art.title}" loading="lazy">
          </div>
          <div class="blog-body">
            <span class="blog-category ${art.categoryColor}">${art.category}</span>
            <h3 class="blog-title">${art.title}</h3>
            <p class="blog-excerpt">${art.excerpt}</p>
            <div class="blog-meta">
              <span>${formatDate(art.date)}</span>
              <span>·</span>
              <span>${art.readtime} min lettura</span>
              ${accessBadge(art.access)}
            </div>
          </div>
        </a>
      `;
    });
    html += `</div>`;
  }

  container.innerHTML = html;

  // Re-run reveal observer on new elements
  container.querySelectorAll('.blog-card').forEach((el, i) => {
    el.classList.add('reveal');
    setTimeout(() => el.classList.add('visible'), 100 + i * 120);
  });
}

// ─── Render full blog index (all articles, grid) ──────────────────────────────

function renderBlogIndex() {
  const container = document.getElementById('blogIndexGrid');
  if (!container) return;

  const countEl = document.getElementById('articleCount');
  if (countEl) countEl.textContent = ARTICLES.length;

  if (ARTICLES.length === 0) {
    container.innerHTML = '<p class="blog-loading">Nessun articolo ancora. Torna presto!</p>';
    return;
  }

  let html = '';
  ARTICLES.forEach((art, i) => {
    html += `
      <a href="${art.slug}.html" class="blog-card reveal" style="transition-delay:${i * 0.08}s">
        <div class="blog-img">
          <img src="${art.image}" alt="${art.title}" loading="lazy">
        </div>
        <div class="blog-body">
          <span class="blog-category ${art.categoryColor}">${art.category}</span>
          <h3 class="blog-title">${art.title}</h3>
          <p class="blog-excerpt">${art.excerpt}</p>
          <div class="blog-meta">
            <span>${formatDate(art.date)}</span>
            <span>·</span>
            <span>${art.readtime} min lettura</span>
            ${accessBadge(art.access)}
          </div>
        </div>
      </a>
    `;
  });

  container.innerHTML = html;

  // Trigger reveal
  setTimeout(() => {
    container.querySelectorAll('.reveal').forEach(el => {
      const observer = new IntersectionObserver(entries => {
        entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); observer.unobserve(e.target); } });
      }, { threshold: 0.05 });
      observer.observe(el);
    });
  }, 50);
}

// ─── Init ─────────────────────────────────────────────────────────────────────

document.addEventListener('DOMContentLoaded', () => {
  renderHomePreview();
  renderBlogIndex();
});
